# Generated by Django 5.1.5 on 2025-02-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_contact_genre_movie_person_video_delete_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'film', 'verbose_name_plural': 'filmler'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'shexs', 'verbose_name_plural': 'shexsler'},
        ),
        migrations.AddField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='bawliq'),
        ),
        migrations.AlterField(
            model_name='person',
            name='duty_type',
            field=models.CharField(choices=[('1', 'Crew'), ('2', 'Cast'), ('3', 'Director'), ('4', 'Writer')], max_length=1, verbose_name='Vezife'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Cinsiyyet'),
        ),
    ]
